export const experience = [
  {
    id: 1,
    company: "LG Soft India",
    designation: "Sr. Research Engineer",
    startYear: 2024,
    endYear: "NA",
    currentOrg: true,
  },
  {
    id: 2,
    company: "IQVIA",
    designation: "Application Developer",
    startYear: 2022,
    endYear: 2024,
    currentOrg: false,
  },
  {
    id: 3,
    company: "Quinnox Consultancy Services",
    designation: "Senior Consultant",
    startYear: 2019,
    endYear: 2022,
    currentOrg: false,
  },
  {
    id: 4,
    company: "Mindtree Privated Limited",
    designation: "Module Lead",
    startYear: 2018,
    endYear: 2019,
    currentOrg: false,
  },
  {
    id: 5,
    company: "IMS Health",
    designation: "Application Developer",
    startYear: 2016,
    endYear: 2018,
    currentOrg: false,
  },
  {
    id: 6,
    company: "IGATE Global Solutions",
    designation: "Sr. Software Engineer",
    startYear: 2014,
    endYear: 2016,
    currentOrg: false,
  },
];

export const education = [
  {
    id: 1,
    school: "Visvesvaraya Technological University",
    course: "Bachelor Of Engineering",
    startYear: "2009",
    endYear: "2014",
  },
  {
    id: 2,
    school: "PES PU College",
    course: "Pre-University Course",
    startYear: "2007",
    endYear: "2009",
  },
  {
    id: 3,
    school: "Gandhi High School",
    course: "Secondary School Leaving Certificate",
    startYear: "2006",
    endYear: "2007",
  },
];

export const skills = [
  { id: 1, title: "HTML5" },
  { id: 2, title: "CSS3" },
  { id: 3, title: "JavaScript" },
  { id: 4, title: "React" },
  { id: 5, title: "Redux" },
  { id: 6, title: "TailwindCSS" },
  { id: 7, title: "DaisyUI" },
  { id: 8, title: "MongoDB" },
  { id: 9, title: "DB2" },
  { id: 10, title: "MySQL" },
  { id: 11, title: "NodeJS" },
  { id: 12, title: "Express.JS" },
  { id: 13, title: "AS400" },
];
